language: python

matrix:
  include:
    - name: "Python 3.8 on Ubuntu Xenial"
      os: linux
      python:
        - 3.6
        - 3.7
        - 3.8
        - 3.9
    - name: "Python on macOS"
      os: osx
      osx_image: xcode12.2
      language: shell

cache: pip

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install gcc || (brew upgrade gcc && brew cleanup gcc)
  elif [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-get update -qq
    sudo apt-get install -qq gfortran make
  fi

install:
  - pip3 install -r requirements-travis.txt

script:
  - which python3
  - python3 --version
  - python3 setup.py build
  - python3 setup.py install

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/55cf16b611593edcb09d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
