# cliff.toml

[changelog]
header = """
# Changelog

All notable changes to the **AIMBAT** project will be documented in this file.

"""

body = """
{% if version %}\
    {% if previous.version %}\
        ## [{{ version | trim_start_matches(pat="v") }}](https://github.com/pysmo/aimbat/compare/{{ previous.version }}...{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
    {% else %}\
        ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
    {% endif %}\
{% else %}\
    ## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}**({{ commit.scope }})** {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | split(pat="\n") | first | upper_first }}\
    {% endfor %}
{% endfor %}\n
"""

trim = true

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false

commit_preprocessors = [
    { pattern = '\r', replace = "" },
    { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](https://github.com/pysmo/aimbat/issues/${2}))" },
]

# The categorization logic
commit_parsers = [
    { message = "^.*\\(deps(-dev)?\\).*", skip = true },
    { message = "^Merge", skip = true },
    { message = "Signed-off-by: dependabot\\[bot\\]", skip = true },
    { message = "Potential fix for code scanning alert", skip = true },
    { message = "^feat", group = "ğŸš€ New Features" },
    { message = "^fix", group = "ğŸ› Bug Fixes" },
    { message = "^perf", group = "âš¡ Performance Improvements" },
    { message = "^docs", group = "ğŸ“š Documentation" },
    { message = "^refactor", group = "ğŸ”§ Refactoring" },
    { message = "^test", group = "ğŸ§ª Testing" },
    { message = "^style", group = "ğŸ¨ Styling" },
    { message = "^chore", group = "ğŸ“¦ Miscellaneous" },
    { message = "^ci|^build", group = "âš™ï¸ DevOps & Infrastructure" },
    { message = ".*uv.lock", group = "âš™ï¸ DevOps & Infrastructure" },
    { message = ".*", group = "ğŸ” Other Changes" },
]

protect_breaking_commits = false
filter_commits = false
# Sort order
tag_pattern = "v[0-9].*"
skip_tags = "beta|alpha"
ignore_tags = ""
sort_commits = "oldest"
