[project]
site_name = "AIMBAT"
site_description = "Aimbat documentation."
site_author = "Simon Lloyd"
site_url = "https://aimbat.pysmo.org/"
copyright = """
Copyright &copy; 2012 - 2026 Simon Lloyd
"""
repo_name = "pysmo/aimbat"
repo_url = "https://github.com/pysmo/aimbat"
nav = [
  { "Home" = "index.md" },
  { "First steps" = [
    {"Installation" = "first-steps/installation.md"},
    {"Data & Conventions" = "first-steps/data.md"},
    {"Workflow & Strategy" = "first-steps/workflow.md"},
  ] },
  { "Usage" = [
    {"Using AIMBAT" = "usage/index.md"},
    "usage/cli.md",
    "usage/gui.md",
  ] },
  { "API reference" = [
    "api/index.md",
  ] },
 { "Getting Help" = "help.md"},
 {"Contributors" = "contributors.md"},
 {"Changelog" = "changelog.md"},
]

extra_css = [
  "css/mermaid.css",
  "css/asciinema-player.css",
  "https://unpkg.com/katex@0/dist/katex.min.css",
  # "css/mkdocstrings.css"
  # "css/material.css",
]
extra_javascript = [
  "javascripts/asciinema-player.min.js",
  "javascripts/katex.js",
  "https://unpkg.com/katex@0/dist/katex.min.js",
  "https://unpkg.com/katex@0/dist/contrib/auto-render.min.js",
 ]

[project.theme]
# variant = "classic"
#custom_dir = "overrides"
#favicon = "images/favicon.png"
language = "en"
features = [
  "announce.dismiss",
  "content.action.edit",
  #"content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  # "header.autohide",
  # "navigation.expand",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.instant.progress",
  "navigation.path",
  "navigation.prune",
  # "navigation.sections",
  "navigation.tabs",
  # "navigation.tabs.sticky",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "toc.follow",
  #"toc.integrate",
]

[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "indigo"
accent = "purple"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "indigo"
accent = "purple"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

#[project.theme.font]
#text = "Inter"
#code = "Jetbrains Mono"

[project.theme.icon]
#logo = "lucide/smile"
repo = "fontawesome/brands/github"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/pysmo/aimbat"

[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
default_lang = "python"
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
[project.plugins.mkdocstrings.handlers.python]
paths = ["src"]
inventories = [
  "https://docs.pysmo.org/objects.inv",
  "https://docs.python.org/3/objects.inv",
  "https://numpy.org/doc/stable/objects.inv",
  "https://docs.scipy.org/doc/scipy/objects.inv",
  "https://matplotlib.org/stable/objects.inv",
]
[project.plugins.mkdocstrings.handlers.python.options]
allow_inspection = true
backlinks = "tree"
# docstring_section_style = "list"
docstring_style = "google"
# force_inspection = true
inherited_members = true
parameter_headings = false
modernize_annotations = true
separate_signature = true
show_bases = true
show_inheritance_diagram = false
show_overloads = false
show_source = true
show_signature_annotations = true
show_symbol_type_heading = true
show_symbol_type_toc = true
signature_crossrefs = true
[project.plugins.mkdocstrings.handlers.python.options.extra]
trim_doctest_flags = true
type_parameter_headings = true
